packages:
  - packages/*
  - libs/*
  - apps/*

catalog:
  '@guiiai/logg': ^1.2.5-beta.2
  '@unbird/eslint-config': ^1.0.2
  '@unbird/result': ^1.1.1
  '@xsai-ext/providers-cloud': ^0.4.0-beta.4
  '@xsai-ext/providers-local': ^0.4.0-beta.4
  '@xsai/embed': ^0.4.0-beta.4
  vue-sonner: ^2.0.9

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - bufferutil
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - websocket
